### ISSUE TITLE
Загрузка тестов

### ISSUE THREAD

**Issue by Kamo98** [Kamo98/DIPLOM_NEW#2]
Сейчас при загрузке тестов имена входного и выходного файлов одного теста должны быть идентичными. Необходимо сделать метод по загрузке тестов более "умным"

**Comment by Demid5** [comment]
имена входного и выходного  теста не обязательно должны быть идентичными
их можно вводить в систему независимо в отсортированном порядке
map нам в помощь 
к каждому входному тесту приписывая нужное расширение
